### ISSUE TITLE
Outdated link to LoFTR indoor_ds weights

### ISSUE THREAD

**Issue by v-pnk** [GrumpyZhou/image-matching-toolbox#11]
Hi @GrumpyZhou !

It seems that the authors of LoFTR released [new indoor_ds checkpoint](https://drive.google.com/drive/folders/1xu2Pq6mZT5hmFgiYMBT9Zt8h1yO-3SIp?usp=sharing) for their model, and the old one was deleted from Google Drive. As a result, download.sh returns "Access denied" error.

**Comment by GrumpyZhou** [comment]
Hi @v-pnk ,

Thanks for reporting this bug. I pushed the fix in the latest commit (4f54a61). Can you check whether this is all good now?

**Comment by v-pnk** [comment]
Hi @GrumpyZhou,
Yes, download.sh now runs without any problem.

Thank you!
