### ISSUE TITLE
Unable to execute Quick Testing code

### ISSUE THREAD

**Issue by uly94** [GrumpyZhou/image-matching-toolbox#13]
I am unable to execute the quick testing code shown in readme.md
I've imported all the files as a PyCharm project, then I installed all the required packages using Conda, I created the following file to execute the image-matching-toolbox, but I have this error... (in addition, there is NO file plot_matches.py inside immatch.utils)
![image](https://user-images.githubusercontent.com/18552295/136973874-46c24456-254f-41e9-bf87-c7f11df17d7c.png)

Waiting your answer, thank you in advance

**Comment by GrumpyZhou** [comment]
Hi @uly94 ,

Can you show me your thrid_party/caps folder? Have you run `git submodule update --init` already?

**Comment by GrumpyZhou** [comment]
Can you post the errors please?
