### ISSUE TITLE
SIFT+SuperGlue

### ISSUE THREAD

**Issue by szgy66** [GrumpyZhou/image-matching-toolbox#21]
Hi, thank you for coming up with this great project! I have been working on this project recently, and superglue really feels like the best matching method at present. I would like to ask if you plan to release the combination of SIFT + Superglue? thanks!

**Comment by GrumpyZhou** [comment]
Hi, 

As far as I know, SuperGlue authors didn't release a SuperGlue version that was trained with SIFT features. If there's a publicly available model, then I will consider integrate it into this toolbox.
