### ISSUE TITLE
"Visualize matches of loftr" error: "AttributeError: 'Namespace' object has no attribute 'no_match_upscale'"

### ISSUE THREAD

**Issue by yangmh66** [GrumpyZhou/image-matching-toolbox#24]
When running the "visualize_matches_on_example_pairs.ipynb", 
only the "loftr" method got an "AttribureError" like this:
![image](https://user-images.githubusercontent.com/17701158/167121243-3246cca7-f2b9-4ca4-9d21-1c136ae93ccc.png)

the other methods all passed!

**Comment by GrumpyZhou** [comment]
Hi @yangmh66 ,

Thanks for reporting the bug. 
Can you try it now? After pull the new commit.
