### ISSUE TITLE
Prepare Image Pairs

### ISSUE THREAD

**Issue by zhubingerdai** [GrumpyZhou/image-matching-toolbox#26]
bash download.sh：
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1T2c3DHJlTdRpo_Y3Ad4AH8p4tS7cOyjP (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0d00812cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
unzip:  cannot find or open pairs.zip, pairs.zip.zip or pairs.zip.ZIP.

**Comment by GrumpyZhou** [comment]
@zhubingerdai  

I can not reproduce your error sorry.. I feel this is your local issue..

```
gdown --id 1T2c3DHJlTdRpo_Y3Ad4AH8p4tS7cOyjP
...
Downloading...
From: https://drive.google.com/uc?id=1T2c3DHJlTdRpo_Y3Ad4AH8p4tS7cOyjP
To: pairs.zip
100%|████████████████████████████████| 6.49M/6.49M [00:00<00:00, 81.3MB/s]
...
```

**Comment by zhubingerdai** [comment]
I think you're right. I tried many ways to solve it

**Comment by zhubingerdai** [comment]
Can pair.zip be put on your Github?

**Comment by GrumpyZhou** [comment]
It is feasible but unless it is necessary I prefer to keep the repo small.
