### ISSUE TITLE
How do I add my own methods to test？

### ISSUE THREAD

**Issue by zhubingerdai** [GrumpyZhou/image-matching-toolbox#27]
I copied the loftr code to add the required files, but when running my code failed: 
KeyError: 'block_type'
Self. block_type = config['block_type'], which is the argument in my code

**Comment by GrumpyZhou** [comment]
The information your provided is not sufficient for me to understand what the situation is.

**Comment by zhubingerdai** [comment]
For example, I replaced "attention" in "loftr" with "quardtree attention". Then I put the code in your code like "loftr". KeyError: 'block_type'     https://github.com/Tangshitao/QuadtreeAttention

**Comment by GrumpyZhou** [comment]
Might be related to missing config of 'block_type' in the config file. Can you check whether this block_type is used in your model and has been configured in the conf? Btw, next time can you post the full error? It is out of track where this key error  happens.

**Comment by zhubingerdai** [comment]
Ok, thank you. The problem has been solved. It is indeed a configuration problem. But the test results are all 0. What do you think might be the problem?

**Comment by GrumpyZhou** [comment]
Make sure you load the pretrained weights properly. You can also debug by just by printing the number of matches , something like that ... If your problem is solved then please close the issue.

**Comment by zhubingerdai** [comment]
self.model(batch) It's not loaded  model，why？‘self.model = LoFTR_(config=conf)‘ is   right
       
 def match_inputs_(self, gray1, gray2):
        batch = {'image0': gray1, 'image1': gray2}
        self.model(batch)
        kpts1 = batch['mkpts0_f'].cpu().numpy()
        kpts2 = batch['mkpts1_f'].cpu().numpy()

**Comment by zhubingerdai** [comment]
-  There is no problem with my code and training results in the loftr test code, Mconf and KPTS have values, is it because of the size of the training picture? Can't extract key points from Hpatch?

**Comment by zhubingerdai** [comment]
'model = PL_LoFTR(config, pretrained_ckpt=args. Ckpt_path, profiler=profiler, dump_dir=args. Dump_dir)' in test.py of loftr,
In your code: 'self.model = LoFTR_(config=conf)'.
Is that the reason?I am very confused

**Comment by zhubingerdai** [comment]
I found the cause, but I don't know how to fix it. This is because several 'class' in my ’transformer. py‘ do not run in your code, but test.py in loftr does.
