### ISSUE TITLE
python -m immatch.eval_inloc 

### ISSUE THREAD

**Issue by zhubingerdai** [GrumpyZhou/image-matching-toolbox#28]
File "/home/szw/image-matching-toolbox-main/immatch/eval_inloc.py", line 5, in <module>
    from third_party.hloc.hloc.localize_inloc import localize_with_matcher
ImportError: cannot import name 'localize_with_matcher'

'localize_with_matcher' is not really in 'localize_inloc.py',Did you make a mistake?

**Comment by GrumpyZhou** [comment]
@zhubingerdai 

Can you check which hloc you are using? The implementation of localize_with_matcher is here:

https://github.com/GrumpyZhou/Hierarchical-Localization/blob/3c8abad67f8c15a7da3cff01824af4110a99c978/hloc/localize_inloc.py#L187-L190
