### ISSUE TITLE
aachen evaluation

### ISSUE THREAD

**Issue by wolf943134497** [GrumpyZhou/image-matching-toolbox#3]
Hi @GrumpyZhou   Thanks for your great works! 

I use patch2pix + superglue as matcher for aachen evaluation,  and use eval_aachen.py script.  I can get keypoints.h5 and matches.h5, but an error was encountered while running triangulation, the error as follows: 
"Keypoint format not supported"

I find the format slightly different from the hloc, any suggestion?  Did you test patch2pix + superglue on aachen ? Thanks!

**Comment by GrumpyZhou** [comment]
Hi @wolf943134497,

Yes, i tested patch2pix+superglue on aachen as shown in the paper. I have not encountered this error before. Can you show me your config for  patch2pix+superglue on aachen and the command for the evaluation ?

**Comment by wolf943134497** [comment]
> Hi @wolf943134497,
> 
> Yes, i tested patch2pix+superglue on aachen as shown in the paper. I have not encountered this error before. Can you show me your config for patch2pix+superglue on aachen and the command for the evaluation ?

Hi Thanks for your quick reply!

I just use the config as follows:

default: &default
    class: 'Patch2PixRefined'
    ckpt: 'image-matching-toolbox/third_party/patch2pix/pretrained/patch2pix_pretrained.pth'
    imsize: 1024
coarse_default: &coarse_default
    name: 'SuperGlue'
    weights: 'outdoor'    
    sinkhorn_iterations: 50
    max_keypoints: 4096
    nms_radius: 4
    imsize: 1024
aachen:
    <<: *default
    match_threshold: 0.1
    imsize: 1600 
    rthres: 48
    coarse:
        <<: *coarse_default
        match_threshold: 0.1
        imsize: 1600
***************************************************************************************
my code :
    # Initialize Model
    config_file = 'configs/patch2pix+superglue.yml'
    with open(config_file, 'r') as f:
        args = yaml.load(f, Loader=yaml.FullLoader)['aachen']
        class_name = args['class']
        print(f'Method:{class_name} Args: {args}')    
    model = immatch.__dict__[class_name](args)
    print('model:',model)
    matcher = lambda im1, im2: model.match_pairs(im1, im2)
       
    dataset_dir = Path('data')
    im_dir = dataset_dir / 'images/'
    output_dir = Path('output')
    
    # Load db & query pairs
    db_pairs_path = output_dir / 'pairs-db-covis20.txt'
    query_pairs_path = output_dir / 'pairs-query-vlad20.txt'
    pair_list = load_pairs(db_pairs_path, query_pairs_path)
    if not pair_list:
        return

    
    # Match pairs
    match_pairs_exporth5(pair_list, matcher, im_dir, output_dir) 
    
    
    # Extract keypoints
    
    process_matches_and_keypoints_exporth5(
        pair_list, output_dir, output_dir )
    
    # Localization
    #init_empty_sfm(args)
    result_sfm = Path('output') / 'result_sfm'
    empty_sfm = Path('output') / 'sfm_base'
    result_dir = output_dir
    colmap = 'colmap'
    reconstruct_database_pairs(result_sfm, empty_sfm, im_dir, db_pairs_path, result_dir, colmap)
    localize_queries(result_sfm, dataset_dir, query_pairs_path, result_dir)
       
        
if __name__ == '__main__':    
    parser = argparse.ArgumentParser(description='Localize Aachen Day-Night')
    parser.add_argument('--gpu', '-gpu', type=str, default=0)
    parser.add_argument('--config', type=str, default=None)
    parser.add_argument('--prefix', type=str, default=None)    
    
    args = parser.parse_args()
    
    eval_aachen(args)

**************************************************************************************
I just want to get the localize_queries results, and test the pipeline is right or not.

I get init_empty_sfm by  sfm. I follow the pipeline as hloc, and just change the matcher. The feature and matches can import the colmap database.

Thanks!

**Comment by GrumpyZhou** [comment]
Um so you used my code to generate the matches and used original hloc repo to import matches and features? Am i understanding it correctly?

**Comment by wolf943134497** [comment]
> Um so you used my code to generate the matches and used original hloc repo to import matches and features? Am i understanding it correctly?

sorry for the unclear description, I use your code to generate the matches and use your script localize_sfm_helper.py to import matches and features, the hloc are also your repo.

Thanks!

**Comment by GrumpyZhou** [comment]
I don't understand in your posted code 
````
reconstruct_database_pairs(result_sfm, empty_sfm, im_dir, db_pairs_path, result_dir, colmap)
localize_queries(result_sfm, dataset_dir, query_pairs_path, result_dir)
````
In the original code, the input argument is different from what you are using:

https://github.com/GrumpyZhou/image-matching-toolbox/blob/6ec826d520464b5a12a7cb430d9eeee09f78f8e4/immatch/utils/localize_sfm_helper.py#L117

Apart from this, i also found something not correct in your config, since to evaluate patch2pix + superglue  on aachen, you need to perform quantization (we also mentioned it in the paper). 
Without quantization, errors might occur during the triangulation or you get much worse accuracy. This is because patch2pix regressed matches are not repeatable compared to keypoint-based methods. 

So to help you get this out, i will update the repo by including the configuration that i used and the running command tonight or tomorrow. Since i still need to work on something else before i touch this.

**Comment by wolf943134497** [comment]
> I don't understand in your posted code
> 
> ```
> reconstruct_database_pairs(result_sfm, empty_sfm, im_dir, db_pairs_path, result_dir, colmap)
> localize_queries(result_sfm, dataset_dir, query_pairs_path, result_dir)
> ```
> 
> In the original code, the input argument is different from what you are using:
> 
> https://github.com/GrumpyZhou/image-matching-toolbox/blob/6ec826d520464b5a12a7cb430d9eeee09f78f8e4/immatch/utils/localize_sfm_helper.py#L117
> 
> Apart from this, i also found something not correct in your config, since to evaluate patch2pix + superglue on aachen, you need to perform quantization (we also mentioned it in the paper).
> Without quantization, errors might occur during the triangulation or you get much worse accuracy. This is because patch2pix regressed matches are not repeatable compared to keypoint-based methods.
> 
> So to help you get this out, i will update the repo by including the configuration that i used and the running command tonight or tomorrow. Since i still need to work on something else before i touch this.

I also change the  the function variables in localize_sfm_helper.py, just write it directly in your code.  I also perform quantization by set  qt_psize = 48, qt_dthres = 4 ,sc_thres = 0.25 in code.  I will check my code and h5 file.

Looking forward to your updates, Thanks for your great works again, it is very meaningful !

**Comment by GrumpyZhou** [comment]
Hey,  can you try with my example command in readme for evaluating patch2pix+superglue  on aachen? Please  inform me here if you succeed with it. Thanks~

**Comment by wolf943134497** [comment]
> Hey, can you try with my example command in readme for evaluating patch2pix+superglue on aachen? Please inform me here if you succeed with it. Thanks~

I will  try with your example command  for evaluating patch2pix+superglue on aachen, I'll give you feedback. Thanks~

**Comment by wolf943134497** [comment]
> > Hey, can you try with my example command in readme for evaluating patch2pix+superglue on aachen? Please inform me here if you succeed with it. Thanks~
> 
> I will try with your example command for evaluating patch2pix+superglue on aachen, I'll give you feedback. Thanks~

@GrumpyZhou   Hi   The code runs successfully! Thanks~

**Comment by GrumpyZhou** [comment]
Hi @TruongKhang,

I do not remember the exact time now but yes it is taking a lot of time (* days) to run the whole evaluation on Aachen due to the large number of pairs.

**Comment by TruongKhang** [comment]
Thank you @GrumpyZhou. Also, I have one more question. I wonder how to get the results `Local Feature Evaluation on Night-time Queries` from the table in your paper. This current code produced the results of `Full Localization with HLOC`, am I right?

**Comment by GrumpyZhou** [comment]
Hi @TruongKhang , 

I just uploaded the config in this commit [e3801b6 ](https://github.com/GrumpyZhou/image-matching-toolbox/commit/e3801b66380e248de1c5c387e2260a779a3b70be).

**Comment by TruongKhang** [comment]
Thank you so much for your engaging discussion! I wish you the best in your research :D
