### ISSUE TITLE
Is the data size of the test fixed?

### ISSUE THREAD

**Issue by zhubingerdai** [GrumpyZhou/image-matching-toolbox#30]
For example, the input of loftr is 480 x 480?

**Comment by GrumpyZhou** [comment]
It depends on how you config. By default config in this repo, it resize so that the image shorter side is 480.  See #20 for detailed discussion about LoFTR reproducing.

**Comment by zhubingerdai** [comment]
ok,I want to ask you a question:
If I want to set the image size to a fixed value, say 480×480, can you set it in your code?
