### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by FlyFish-space** [GrumpyZhou/image-matching-toolbox#31]
First of all, thank you for your excellent work. I run eval__ hpatches after installing the environment, there is a ModuleNotFound Error:
`ModuleNotFoundError: No module named 'third_party.caps.CAPS'`
I think it may be the problem of submodules. Some submodules can be imported normally, such as d2net, r2d2

**Comment by GrumpyZhou** [comment]
Hi @FlyFish-space, 

Did you manage to solve the issue? If not can you show me the tree of you third_party/ directory?
