### ISSUE TITLE
Could you please guide how to set the evaluation for Aachen Night Only? 

### ISSUE THREAD

**Issue by GabbySuwichaya** [GrumpyZhou/image-matching-toolbox#33]
Thank you very much for this toolbox. 

Here I would like to ask the question of how to set the evaluation for Aachen Night only with the default retrieved image list? 
Could you please guide how to do this? I am very new to the system.

**Comment by GrumpyZhou** [comment]
Hi @GabbySuwichaya ,

The way to control night-only and full evaluation is by setting different db pairs for reconstruction and query pairs for testing. 
As an example: 
https://github.com/GrumpyZhou/image-matching-toolbox/blob/47e352943747472c9730eb40cba433db6acbf832/configs/patch2pix.yml#L38-L47

You can download the night benchmark pairs by following [this section](https://github.com/GrumpyZhou/image-matching-toolbox/blob/main/docs/evaluation.md#prepare-image-pairs).

**Comment by GabbySuwichaya** [comment]
@GrumpyZhou , Thank you for this. 

Could you maybe share the two files ('pairs-db-night_benchmark.txt', 'pairs-query-night_benchmark.txt') that are used...? 

I would like to check some of my settings... 

Also, if I use the original "image_pairs_to_match.txt"... How to set the toolbox for this? Could you please kindly suggest the good way to do it....?

**Comment by GrumpyZhou** [comment]
Did you follow the section I said above to download the pairs? It's right there.

Those pairs are split from image_pairs_to_match.txt and if you check the contents they are the same.

How to do that is  exactly shown in the the code I posted above.
As I said it is by setting the pairs in the config that's all. You just need to change pairs in the config like that.

**Comment by GabbySuwichaya** [comment]
Thank you so much! 

Yes, I see. 
Now I run it and got a similar result.  :)
