### ISSUE TITLE
--colmap $COLMAP_PATH

### ISSUE THREAD

**Issue by GooGoowanttotang** [GrumpyZhou/image-matching-toolbox#35]
I installed pycolmap0.3.0 through pip, but I'm not sure what to fill in.I tried the installation path of pycolmap, but it didn't work.

**Comment by ewrfcas** [comment]
Hi, how to solve this problem?

**Comment by GooGoowanttotang** [comment]
> Hi, how to solve this problem?

You should install colmap and choose its path

**Comment by ewrfcas** [comment]
Thanks!
