### ISSUE TITLE
Test loftr in aachen

### ISSUE THREAD

**Issue by autostudiolea** [GrumpyZhou/image-matching-toolbox#42]
Hi! I’m trying to use your great work to eval loftr in aachen.
But it seems like a huge work, my running state is shown below, It doesn't call the gpu to handle....

100%|██████████| 131615/131615 [00:01<00:00, 99454.57it/s]
  0%|          | 0/102817 [00:00<?, ?it/s]
Load match file, existing matches 0
Start matching, total 102817 pairs...
  0%|          | 3/102817 [01:27<831:08:45, 29.10s/it]

Is this a normal phenomenon? If not, could you tell me how to solve it?

my args is:

--gpu
0
--config
loftr
--colmap
F:/work/COLMAP-3.8-windows-cuda/COLMAP.bat
--benchmark_name
aachen

my config is as follow, only changed the path of ckpt.

default: &default
    class: 'LoFTR'
    ckpt: 'E:/work/image-matching-toolbox-main/pretrained/loftr/myout0.ckpt'
    match_threshold: 0.2
    imsize: -1
    no_match_upscale: False
aachen:
    <<: *default
    match_threshold: 0.0 # Save all matches
    pairs: ['pairs-db-covis20.txt', 'pairs-query-netvlad50.txt']
    npts: 4096
    imsize: 1024
    qt_dthres: 4
    qt_psize: 48
    qt_unique: True
    ransac_thres: [20]
    sc_thres: 0.2 # Filtering during quantization
    covis_cluster: True

**Comment by GrumpyZhou** [comment]
Hi @autostudiolea,

I would suggest to debug it first with a pair of images, since the matcher is initialised in the same way. And in theory it automatically use the available GPU device: https://github.com/GrumpyZhou/image-matching-toolbox/blob/76a865780919ae87cabc050b4569cf0feb11007d/immatch/modules/base.py#L49 .

**Comment by autostudiolea** [comment]
Thank you for your response! I had just configured the virtual environment incorrectly    T T
Now I can finish the task in a day
