### ISSUE TITLE
The possibilities of python to C++

### ISSUE THREAD

**Issue by zanbowen** [GrumpyZhou/image-matching-toolbox#45]
Patch2Pix achieved amazingly good results on our dataset. Therefore, we are interested in taking the work further and deploying it on our C++ project. 

Unfortunately, I am not familiar with this process and would like to ask for your opinion and advice on this. I've researched that the methods involved include compiling the python program as '.DLL' and using C++ calls, and I'm not sure if this will affect efficiency. Or reading and understanding the program in depth and rewriting it in C++, which would be a very challenging work. 

Thank you very much for your suggestions and help!

**Comment by GrumpyZhou** [comment]
Hi @zanbowen ,

I am glad to hear that our work works well on your dataset. However, I also have limited experience with importing python model into C++ project. But I found this [answer](https://stackoverflow.com/questions/59806553/pytorch-model-to-c) is quite helpful. I have only worked with Torchscript inside a small C++ app before, but it works properly if your model is not super complicated. Maybe you can simply  try first whether you can export the pretrained patch2pix model as torchscript. Sorry for the limited help here and I wish you good luck !
