### ISSUE TITLE
Feature point annotation tool

### ISSUE THREAD

**Issue by DoongLi** [GrumpyZhou/image-matching-toolbox#46]
Hi, I want to labeling some image pair feature point use my data, is there have any tools can do it ?
best

**Comment by GrumpyZhou** [comment]
What do you mean by labeling feature points here? You mean detecting
keypoints for you images ?

**Comment by DoongLi** [comment]
Actually, I want to test and evalute different image matching methods, so I would labeling some feature point by hand , and use it as groundtruth.

**Comment by GrumpyZhou** [comment]
Do you only annotate  the feature points as the ground truth keypoints or
you also provide ground truth matches ?

Usually the existing benchmark evaluates the matches by using them to
estimate geometric transformations for evaluation.

**Comment by DoongLi** [comment]
Sorry, I want to evaluate it by use feature points and matchs, but i dont know how to generate them because my data has a lot of light changes

**Comment by GrumpyZhou** [comment]
Have you already tried to use the methods supported in this repo and see whether they can give you good matches on your data? Here's an example how you can use them to match any image pair: [visualize_matches_on_example_pairs.ipynb](https://github.com/GrumpyZhou/image-matching-toolbox/blob/main/notebooks/visualize_matches_on_example_pairs.ipynb).

**Comment by DoongLi** [comment]
Not yet, but I will try later, Do you think is make sense for research paper which use some open source image matching methods to get some pre result and select good match result by hand, then use this result as gt for evaluation.

**Comment by GrumpyZhou** [comment]
Hm I never seen geometric matching ground-truth hand-picked by human. It is not as accurate as matches computed by geometric transformations. Also is not an efficient way to get GTs since one image pair you can have lots of feature matches.

**Comment by DoongLi** [comment]
How to achieve matches computed by geometric transformations？ My data just some image pairs, no depth information and could not do SFM

**Comment by GrumpyZhou** [comment]
If you do not have any pose information it's not possible I think. But if your images are from one scene you can run SfM to get poses. In the case if you do not have GTs for those pairs, why you have to stick to those pairs for evaluation? There are common benchmarks to eval matching models and why not use them ? Sorry I don't know details about your final goal. But I guess there's not much more I can help :D.

**Comment by DoongLi** [comment]
Thx for your reply, I got it, have a great day!
