### ISSUE TITLE
git@github.com: Permission denied (publickey).

### ISSUE THREAD

**Issue by hhmaizi** [GrumpyZhou/image-matching-toolbox#8]
Thanks for this great project. According to the [installation doc](https://github.com/GrumpyZhou/image-matching-toolbox/blob/main/docs/install.md#installation)  the toolbox should be install using ssh, which is impossible for users interested  to add ssh-key to this project. And offcourse, nonsense. and I have checked the .gitmodules file
`[submodule "third_party/SuperGluePretrainedNetwork"]
        path = third_party/superglue
        url = git@github.com:magicleap/SuperGluePretrainedNetwork.git
[submodule "third_party/caps"]
        path = third_party/caps
        url = git@github.com:GrumpyZhou/caps.git
[submodule "third_party/d2-net"]
        path = third_party/d2net
        url = git@github.com:mihaidusmanu/d2-net.git
[submodule "third_party/r2d2"]
        path = third_party/r2d2
        url = https://github.com/naver/r2d2
        ignore = untracked
[submodule "third_party/sparse-ncnet"]
        path = third_party/sparsencnet
        url = git@github.com:ignacio-rocco/sparse-ncnet.git
[submodule "third_party/hloc"]
        path = third_party/hloc
        url = git@github.com:GrumpyZhou/Hierarchical-Localization.git
        branch = extend_base_dev
`
would you change the url to https, so we can test and use this great project.

**Comment by hhmaizi** [comment]
this is the error log
`
Cloning into '/opt/repo/imm-toolbox/third_party/caps'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:GrumpyZhou/caps.git' into submodule path '/opt/repo/imm-toolbox/third_party/caps' failed
Failed to clone 'third_party/caps'. Retry scheduled
Cloning into '/opt/repo/imm-toolbox/third_party/d2net'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mihaidusmanu/d2-net.git' into submodule path '/opt/repo/imm-toolbox/third_party/d2net' failed
Failed to clone 'third_party/d2net'. Retry scheduled
Cloning into '/opt/repo/imm-toolbox/third_party/hloc'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:GrumpyZhou/Hierarchical-Localization.git' into submodule path '/opt/repo/imm-toolbox/third_party/hloc' failed
Failed to clone 'third_party/hloc'. Retry scheduled
Cloning into '/opt/repo/imm-toolbox/third_party/loftr'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:zju3dv/LoFTR.git' into submodule path '/opt/repo/imm-toolbox/third_party/loftr' failed
Failed to clone 'third_party/loftr'. Retry scheduled
Cloning into '/opt/repo/imm-toolbox/third_party/patch2pix'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:GrumpyZhou/patch2pix.git' into submodule path '/opt/repo/imm-toolbox/third_party/patch2pix' failed
Failed to clone 'third_party/patch2pix'. Retry scheduled
Cloning into '/opt/repo/imm-toolbox/third_party/sparsencnet'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:ignacio-rocco/sparse-ncnet.git' into submodule path '/opt/repo/imm-toolbox/third_party/sparsencnet' failed
Failed to clone 'third_party/sparsencnet'. Retry scheduled
Cloning into '/opt/repo/imm-toolbox/third_party/superglue'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:magicleap/SuperGluePretrainedNetwork.git' into submodule path '/opt/repo/imm-toolbox/third_party/superglue' failed
Failed to clone 'third_party/superglue'. Retry scheduled
Cloning into '/opt/repo/imm-toolbox/third_party/caps'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:GrumpyZhou/caps.git' into submodule path '/opt/repo/imm-toolbox/third_party/caps' failed
Failed to clone 'third_party/caps' a second time, aborting

`

**Comment by GrumpyZhou** [comment]
Hi,

Thanks for reporting the problem. Can you try whether the new commit fix your problem now?

**Comment by hhmaizi** [comment]
Thanks for the immediate response. And the new commit works.

**Comment by hhmaizi** [comment]
It would be great if you modify the Installation.md accordingly. @GrumpyZhou

**Comment by GrumpyZhou** [comment]
@hhmaizi Can you be more specific where am i supposed to change?
Do you mean : 
git clone git@github.com:GrumpyZhou/image-matching-toolbox.git 
-> https://github.com/GrumpyZhou/image-matching-toolbox.git
Or something else?

**Comment by hhmaizi** [comment]
Yes, here [installation](https://github.com/GrumpyZhou/image-matching-toolbox/blob/main/docs/install.md#installation)
`
git clone git@github.com:GrumpyZhou/image-matching-toolbox.git
`
